version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ["./docker-entrypoint.sh"]
    volumes:
      - .:/code
      - ./devops/settings_docker.py:/code/devops/settings.py
    ports:
      - "8000:8000"
    depends_on:
      - db

  ethercalc:
    image: audreyt/ethercalc
    ports:
      - "8001:8000"
    depends_on:
      - redis
  redis:
    image: redis
    volumes: ["./redis:/data"]
    command: redis-server --appendonly yes

  etherpad:
    image: ptman/etherpad
    ports:
      - "8002:9001"
#    volumes:
#      - ./settings.json:/opt/etherpad/settings.json
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "etherpad"
      MYSQL_USER: "etherpad"
      MYSQL_PASSWORD: "etherpad"
    volumes:
      - ./mariadb:/var/lib/mysql
 
