version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ["./docker-entrypoint.sh"]
    volumes:
      - .:/code
      - ./devops/settings_docker.py:/code/devops/settings.py
      - ./ecobasa/ecobasa/default_settings.py:/code/ecobasa/ecobasa/default_settings.py
    ports:
      - "8000:8000"
    depends_on:
      - db
